name: Build
on: 
  push: 
    branches: 
      - main
    paths-ignore: [".github/**"]
  pull_request:
    branches: 
      - main
  workflow_dispatch:

jobs:   
  build:
    name: Build
    runs-on: ubuntu-latest    
    steps:    
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: List files
        run: | 
          ls -l **/*
        
      
