name: Github Actions Demo
on: 
  push: 
    branches: 
      - main
    paths-ignore: [".github/**"]
  schedule:
    - cron: "15 6 * * 0"
  pull_request:
    branches: 
      - main
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        required: true
        description: Which environment would you like to use
        default: Test
        

jobs:   
  hello:
    runs-on: ubuntu-latest
    steps:    
      - name: Say hello
        run: | 
          echo "Hello, world !"
  test:
    runs-on: ubuntu-latest
    environment: Test
    steps:
      - name: Test
        run: echo Testing...
  loadtest:
    runs-on: ubuntu-latest
    environment: Load-Test
    steps:
      - name: Load Test
        run: |
          sleep 15
          echo Load tested
  production:
    runs-on: ubuntu-latest
    needs: [test, loadtest]
    if: ${{inputs.environment == "Production"}}
    steps:
      - name: Step 1
        run: sleep 5 && echo Step 1
      - name: Step 2
        run: sleep 5 && echo Step 2
