name: Github Actions Demo
on: 
  push: 
    branches: 
      - main
    paths-ignore: [".github/**"]
  schedule:
    - cron: "15 6 * * 0"
  pull_request:
    branches: 
      - main
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        options:
          - Prod
          - Test
          - LoadTest
        required: true
        description: Which environment would you like to use
        default: Test
        

jobs:   
  hello:
    runs-on: ubuntu-latest
    steps:    
      - name: Say hello
        run: | 
          echo "Hello, world !"
      
