name: Docker Hello Build
on: 
  push: 
    branches:
      - "main"
    paths: ["hello-world-docker-action/**"]
  workflow_dispatch:    
  
jobs:
  docker:
    runs-on: ubuntu-latest
    name: Greet with Docker
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Run docker
        id: hello-action
        uses: ./hello-world-docker-action
        with:
          who-to-greet: Aurora
      - name: Time from container
        run: "echo The time was ${{ steps.hello-action.outputs.time }} when the action said hello"