name: Reuse other workflow
on: 
  workflow_dispatch:
jobs:
  reuse:
    name: Reuse Hello
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Call the worflows
        id: call
        uses: ./.github/workflows/reusable
        with: 
          who-to-greet: "me"
  use-output:
    name: Display the time output
    runs-on: ubuntu-latest
    needs: reuse
    steps:
      - name: "Say the time"
        run: |
          echo "Time from out-parameter ${{needs.jobs.reuse.outputs.time}}"
  
