name: Reuse other workflow
on: 
  workflow_dispatch:
jobs:
  reuse:
    name: Debug
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Debug
        run: |
          echo "$(pwd)"
          ls -l ./.github/workflows
          echo "Debug output"
          cat  ./.github/workflows/reusable.yml
  call:
    name: Call the worflows
    uses: ./.github/workflows/reusable.yml
    with:
      who-to-greet: "me"
  use-output:
    name: Display the time output
    runs-on: ubuntu-latest
    needs: reuse
    steps:
      - name: "Say the time"
        run: |
          echo "Time from out-parameter ${{needs.jobs.reuse.outputs.time}}"
  
