name: Reuse other workflow
on: workflow_dispatch
jobs:
  reuse:
    name: Reuse Hello
    runs-on: ubuntu-latest
    steps: 
      - name: Call the worflows
        id: call
        uses: ./.github/workflows/reusable.yml
        with: 
          who-to-greet: "me"
  use-output:
    name: Display the time output
    runs-on: ubuntu-latest
    needs: reuse
    steps:
      - name: "Say the time"
        run: |
          echo "Time from out-parameter ${{jobs.reuse.outputs.time}}"
  
